### ISSUE TITLE
(Suggestion) Customize shortcut and font

### ISSUE THREAD

**Issue by happysurf** [WaldiPL/readingList#1]
Will be great for the user customize the shortcut, the font style and size.
Thanks.

**Comment by WaldiPL** [comment]
Unfortunately, there is currently no way to configure shortcuts. Probably this feature will be available in the future. Please follow the bug [1303384](https://bugzilla.mozilla.org/show_bug.cgi?id=1303384)
Currently I do not plan to add the option to change the font. Maybe in the future I will add the option to resize the font. In version 1.2.1 has been changed font, it is now sans serif. IMHO looks better.

**Comment by happysurf** [comment]
San Serif is certainly better than previous one.
Thank you for the info.
