### ISSUE TITLE
Compact mode view

### ISSUE THREAD

**Issue by happysurf** [WaldiPL/readingList#12]
In Compact Mode view, the web site descriptions are too long and cutted, in this way are bad to view.
Maybe is better cut with three dots after 300 px. in width or something like that.
In addition will be great improve the favicon for sites that do not have it (like the Realtek in list).

![compact](https://user-images.githubusercontent.com/13637587/31863159-da3ca9f0-b749-11e7-9dd7-325efa552ca8.png)

**Comment by WaldiPL** [comment]
This will be fixed in the next version.
Pages that do not have favicons use the globe icon. Sometimes Firefox returns the wrong address for pages without favicons, so there is a problem with the icon.
