### ISSUE TITLE
(Suggestion) Sync Reading List

### ISSUE THREAD

**Issue by aserrallerios** [WaldiPL/readingList#13]
Self-explanatory title. Can this be done?

Thanks for the great job!

**Comment by WaldiPL** [comment]
I've tried to add such a possibility, but the maximum size of the database is 100kB, and the maximum size of one element is 8kB.

Currently, the database consists of 3 elements: web pages, thumbnails, settings.
There are 2 problems. 100kB is about 30 complete web pages. 8kB is only 2-3 thumbnails, so only so many pages can be synchronized without any problems. 8kB is also about 30 pages without thumbnails, but the synchronization only part of the database would result in incorrect display of thumbnails.

**Comment by aserrallerios** [comment]
An alternative would be to change the web pages backend to a Bookmark folder (like the "Snooze tab" plugin does). 

I guess this would require a lot of changes, but maybe it's worth it.

The thumbnails can be shown with a best-effort strategy, show thumbnail only if present (i.e. if page was saved locally), otherwise, show host icon.

**Comment by WaldiPL** [comment]
Thanks ,in this way it works well. Soon synchronization should be available.

**Comment by aserrallerios** [comment]
You rock!
