### ISSUE TITLE
Provide a pageAction instead of browserAction (or both)

### ISSUE THREAD

**Issue by nt1m** [WaldiPL/readingList#16]
The "add to reading list" button makes much more sense as a page action in my opinion

**Comment by WaldiPL** [comment]
You can add any page to the list, so I used the `browserAction`, which is displayed by default for each page.

**Comment by nt1m** [comment]
You can also use pageAction.show() on every page.

I think it's better as a page action, because, well, it's a page related action :)

**Comment by WaldiPL** [comment]
I'll try to add `pageAction`, but I'll also leave the `browserAction`.

**Comment by WaldiPL** [comment]
PageAction is available in version 1.4.5. This is disabled by default,  you can change it in options.
