### ISSUE TITLE
Suggestion: favicons

### ISSUE THREAD

**Issue by aserrallerios** [WaldiPL/readingList#18]
Use Google favicon service to resolve favicons of pages that don't have valid thumbnail and favicon (when syncing, for example).

[how to](https://www.labnol.org/internet/get-favicon-image-of-websites-with-google/4404/)

**Comment by WaldiPL** [comment]
This will be available in the next version, but I use icons.better-idea.org

**Comment by aserrallerios** [comment]
Nice!
