### ISSUE TITLE
Page action inactive state

### ISSUE THREAD

**Issue by happysurf** [WaldiPL/readingList#21]
In page action the function appear disabled, in addition the icon appear black instead white like set in toolbar.

![icon](https://user-images.githubusercontent.com/13637587/46546518-921a9f00-c8c9-11e8-959f-a9505427145a.png)

This problem is present with Firefox 63beta.

**Comment by WaldiPL** [comment]
You must enable `Show button in the address bar` in options.

The icon's color has been fixed in version 1.5.1
