### ISSUE TITLE
saving my place within a document

### ISSUE THREAD

**Issue by bburdette** [WaldiPL/readingList#24]
Sometimes I'd like to save my place within a large document so I can return to it later where I left off.  Do FF or Chrome supply hooks that might make this possible?  It would be especially great for PDFs that might be hundreds of pages long.

**Comment by WaldiPL** [comment]
In pdf files you can use the button that creates a link with the current position.
![pdf](https://user-images.githubusercontent.com/2010813/63279166-d2e49200-c2a8-11e9-8a06-e5473716f33d.png)
