### ISSUE TITLE
(Suggestion) Contextual tabs and bookmarks "Add to Reading List"

### ISSUE THREAD

**Issue by aserrallerios** [WaldiPL/readingList#5]
Add to Reading List action on tabs and bookmarks, that includes bookmark folders to add all bookmarks inside a folder to the list. Add all open tabs would be nice too.

**Comment by WaldiPL** [comment]
Currently, there is no possibility to add items to the context menu of bookmarks.
The ability to add all tabs to the list will soon be added.
