### ISSUE TITLE
Slow to remove web sites

### ISSUE THREAD

**Issue by happysurf** [WaldiPL/readingList#6]
When remove a web site in the list the operation is very slow.
In addition sometimes during this action appear for a half second an warning bar to the top impossible to read.
Firefox Nightly on W10.

**Comment by WaldiPL** [comment]
Do you use the latest version of the extension?
How many pages are added to the list?
Do slowdowns also appear in other extensions? Or when using multiple browser tabs?
What CPU do you have and how much RAM?

**Comment by happysurf** [comment]
1. Yes;
2. For the test only 2 or 3 pages;
3. No slowdown in other extension or browser functionality;
4. I have a modern HP laptop with Intel Core I5 + 12 Gb. of RAM + SSD 256 Gb.

With **Rapid Deleting** the operation is very fast and for me is OK;
Otherwise is slow and the **Info bar** in my case never appear or just for an instant.

**Comment by happysurf** [comment]
Also in RSS pages like this https://github.com/Robbendebiene/Gesturefy/commits/master.atom or any other the gestures are performed but the trace doesn't appear.

**Comment by WaldiPL** [comment]
By default, pages are deleted after 2 seconds; this is the time to restore the accidentally deleted page.
"Rapid Deleting" makes the page removed immediately and can not undo this action.

What do you mean by **Info bar**?

**Comment by happysurf** [comment]
OK, that is the delay I was talking about but if works in this way for the undo it's fine.
This is the **Notification bar** (sorry not **Info bar**) in the options but never appear:

![notification bar](https://user-images.githubusercontent.com/13637587/30469267-ae6f7cf2-99ef-11e7-85b5-416303417f3a.png)

**Comment by WaldiPL** [comment]
This bar should appear after 10 seconds on the pages added to the list.

**Comment by happysurf** [comment]
I understand now, but why after 10 seconds, maybe is better after 2 or 3 seconds.

**Comment by WaldiPL** [comment]
This is just a reminder, often after reading the article I forgot to remove it from the list.
If you want to delete a page faster you can use the button on the toolbar.
