### ISSUE TITLE
(Suggestion) Icon for dark skin

### ISSUE THREAD

**Issue by happysurf** [WaldiPL/readingList#7]
Is possible add in the options the use of an inverted toolbar icon (white background with black cross and x ) for dark Personas skin?
Thanks.

**Comment by WaldiPL** [comment]
Currently, there is no such possibility.

EDIT:
It is not possible for the icon color to change automatically, but it can be set manually in the options.

**Comment by WaldiPL** [comment]
In the latest version I added the option to change the button icon theme.

**Comment by happysurf** [comment]
The new white icon is perfectly consistence with Photon inverted ones.
Thanks!
